# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Free Trial(20652769-9ab1-4786-b6da-6d42c61fc480)'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: 'docker login sampleacr123456.azurecr.io -u 00000000-0000-0000-0000-000000000000 -p eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjZLQUM6RUVIUDpUVlpGOk5CNEg6VjdCRzoyQlc0OkxWQk46MlhJWjpWVzNWOlA0RTI6N09GMzpFQlpMIn0.eyJqdGkiOiI5M2ZhNWRmYy1jMGI4LTQyZGQtOTJmMC01MzgwNDMxZTI4ODkiLCJzdWIiOiJsaXZlLmNvbSNzZDE0MTAxOTg0QGdtYWlsLmNvbSIsIm5iZiI6MTYwNjM5NTQ2MiwiZXhwIjoxNjA2NDA3MTYyLCJpYXQiOjE2MDYzOTU0NjIsImlzcyI6IkF6dXJlIENvbnRhaW5lciBSZWdpc3RyeSIsImF1ZCI6InNhbXBsZWFjcjEyMzQ1Ni5henVyZWNyLmlvIiwidmVyc2lvbiI6IjEuMCIsImdyYW50X3R5cGUiOiJyZWZyZXNoX3Rva2VuIiwidGVuYW50IjoiZTBkMjY1MjAtZmVmZS00ZjNkLWFlMTItNDQ2ODkyMzgyZTEyIiwicGVybWlzc2lvbnMiOnsiYWN0aW9ucyI6WyJyZWFkIiwid3JpdGUiLCJkZWxldGUiXSwibm90QWN0aW9ucyI6bnVsbH0sInJvbGVzIjpbXX0.fYqtxF9Ay1hr_GwNun0k3gJP8Nrd08sJZmpH6VKBSc__fiaqPjt7fogF0LC_DOdQAHxoT6AnBdfsyrLoey4K2Jg77p1LDLMttA4ZrkrVeosKY0IClJZ8H8CxQaJYc3pnOC4_fNGEWhg7nB3mc040g78HZUgMZOjft45pWeTJ61iE6rPOxkuDjmFS9UBPRNinejMOThtQ479ECl9v_l1JL81hF51bN3WRIPmssoir1kif8H_8p0dVVe6-sITGg8eHY6o-YxH3vh88WhAFoIjav7_n97VxFPKo-oB0Jv1IPfeTNHVDTqa2J2P6TTct1eOHp8J2JLHB23ayShHGyFkIKw'
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
